# serverless.yml

#组件信息
component: scf # (必选) 组件名称，在该实例中为scf
name: jdscript # (必选) 组件实例名称。

#组件参数配置
inputs:
  name: scf-${name} # 云函数名称，默认为 ${name}-${stage}-${app}
  namespace: default
  enableRoleAuth: true # 默认会尝试创建 SCF_QcsRole 角色，如果不需要配置成 false 即可
  src: 
    src: ./
    exclude:
      - '*.!(js|txt|json)'
      - 'backUp/**'
      - 'icon/**'
  handler: index.main_handler #入口
  runtime: Nodejs12.16 # 运行环境 默认 Nodejs12.16
  region: ap-guangzhou # 函数所在区域
  description: This is a function in ${app} application.
  memorySize: 64 # 内存大小，单位MB
  timeout: 3600 # 超时时间，单位秒
  asyncRunEnable: true # 是否启用异步执行
  retryNum: 0
  events: #触发器
    - timer:
        parameters:
          name: config
          cronExpression: "0 0 * * * * *"
          enable: true
          argument: config
    - timer: #宠汪汪积分兑换京豆
        parameters:
          name: joyreward
          cronExpression: "0 59 7,15,23 * * * *"
          enable: true
          argument: jd_joy_reward
    - timer: #汽车兑换
        parameters:
          name: car_exchange
          cronExpression: "30 59 23 * * * *"
          enable: false
          argument: jd_car_exchange
    - timer: #超市蓝币兑换
        parameters:
          name: blueCoin
          cronExpression: "0 59 23 * * * *"
          enable: false
          argument: jd_blueCoin
    - timer:
        parameters:
          name: cfd
          cronExpression: "0 59 0 * * * *"
          enable: true
          argument: jd_cfd
    - timer:
        parameters:
          name: cfd_pearl
          cronExpression: "50 59 * * * * *"
          enable: true
          argument: jd_cfd_pearl_ex
  environment: #  环境变量
    variables: #  环境变量对象
      TZ: Asia/Shanghai
      JD_USER_AGENT: 'jdapp;android;10.1.0;10;7393467316333616-5653268316839343;network/wifi;model/HLTE203T;addressid/187251643;aid/79d7a3cae5b8a894;oaid/;osVer/29;appBuild/89583;partner/google;eufv/1;jdSupportDarkMode/0;Mozilla/5.0 (Linux; Android 10; HLTE203T Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.159 Mobile Safari/537.36'
      JS_USER_AGENT: 'jdltapp;android;3.7.0;10;7393467316333616-5653268316839343;network/wifi;model/HLTE203T;addressid/484457409;aid/79d7a3cae5b8a894;oaid/;osVer/29;appBuild/1898;psn/ZvBRnNYjd26zc5YC58XAKPAPWE q9I5k|152;psq/10;adk/;ads/;pap/JA2020_3112531|3.7.0|ANDROID 10;osv/10;pv/70.11;installationId/542dd0e6df7f440dbcbf9e19db4df152;jdv/0|kong|t_1003076299_|jingfen|c60ddc693be9497eac4faab6aae0d680|1633270479;ref/com.jd.jdlite.lib.personal.view.fragment.JDPersonalFragment;partner/yingyongbao;apprpd/MyJD_Main;eufv/1;Mozilla/5.0 (Linux; Android 10; HLTE203T Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.126 MQQBrowser/6.2 TBS/045140 Mobile Safari/537.36'
      JX_USER_AGENT: 'jdpingou;android;5.5.2;10;79d7a3cae5b8a894;network/wifi;model/HLTE203T;appBuild/18482;partner/jingdong;;session/655;aid/79d7a3cae5b8a894;oaid/;pap/JA2019_3111789;brand/Hisense;eu/7393467316333616;fv/5653268316839343;Mozilla/5.0 (Linux; Android 10; HLTE203T Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.159 Mobile Safari/537.36'
      PUSH_PLUS_TOKEN: 99184e0471c44f58add1b289cd43fa07
      JD_COOKIE: pt_key=app_openAAJhVGDDADBfllb1r1eHwJOvLwgtIC2OAeJ3it-bY7VzAY5Iszd1ErFe4rgQ4HuHSbJgUne5tsI;pt_pin=15022052312_p;
      FRUIT_BEAN_CARD: true
      FRUITSHARECODES: f0e27ed9b1c74d218d8fae8d17bb6301@ff0fe41355014b6fb7be52b46c097652@4bf14b390d86413b9d8bdaddd99b7cab
      PLANT_BEAN_SHARECODES: mlrdw3aw26j3w5igg2k362mkxijlbq2odafq5za@mlrdw3aw26j3wx3lpdupc73mp4yewsppcl77xlq@olmijoxgmjuty6vlxaick6qgzv6l7gnvbmgqzja
      JDJOY_SHARECODES: hJOwUGoDxjD0x72Ct6Kw16t9zd5YaBeE
      JDSGMH_SHARECODES: T0225KkcRRca8wXeKBuhlvYNfACjVQmoaT5kRrbA
      JDHEALTH_SHARECODES: T0225KkcRRca8wXeKBuhlvYNfACjVQmoaT5kRrbA
      DREAM_FACTORY_SHARE_CODES: MUdRsCXI13_DDYMcnD8v7g==@1Ymft0zzf3SbRwoF-NbSXw==@2uOn4i89AGbdsG_2uwbTAw==
      PETSHARECODES: MTEzMzI0OTE0NTAwMDAwMDA0NDkxMDEwNQ==@MTE1NDAxNzYwMDAwMDAwMzkxMjczNDU=@MTE1NDQ5OTUwMDAwMDAwMzkxMjg4MDE=
      BOOKSHOP_SHARECODES: be9bec5303d44d34b46ad9bce1ce02aa
      JOY_FEED_COUNT: 80
      JD_TRY: 'true'
      JD_TRY_TITLEFILTERS: 教程@软件@英语@辅导@培训@网线@cd@吸顶灯@靠垫@砌墙仪@保护套@安全座椅@大灯@手机壳@理发@吊灯@面漆@油画@国画@晾衣架@赠品@总成
      JD_TRY_PRICE: 300
      JD_TRY_TABID: 3@4@5@7
      JD_TRY_TRIALPRICE: 5
      JD_TRY_APPLYNUMFILTER: 9999999
      JD_TRY_MAXLENGTH: 350
      JD_TRY_PLOG: false
      JD_JOY_REWARD_NAME: 500
      FS_LEVEL: car
      JD_JOIN_ZLC: 'false'